TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += sp2xx.db
DB += sp2xxSetting.db

#protocol files
DATA += sp2xx.proto

#=======================================
include $(TOP)/configure/RULES
